language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: DEPENDENCIES='low'
    - php: 7.2
    - php: 7.2
      env: DEPENDENCIES='low'
    - php: 7.3
    - php: 7.3
      env: DEPENDENCIES='low'
  fast_finish: true

before_install:
  - composer selfupdate

install:
  - if [ "$DEPENDENCIES" != "low" ]; then travis_retry composer update --no-progress --profile --prefer-dist --no-scripts --no-interaction; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then travis_retry composer update --no-progress --profile --prefer-lowest --no-scripts --no-interaction; fi;
  - composer show

script:
   - ./vendor/bin/grumphp run
